<h1>Part A- Create a Notebook to demonstrate NumPy Operations.</h1>

<h5>1. Create an array that starts from the integer 1, ends at 20, incremented by 3.</h5>

In [1]:
import numpy as np
array_1 = np.arange(1, 21, 3)
print(array_1)

[ 1  4  7 10 13 16 19]


<h5>2. Create a new array of shape 3 with random numbers between 0 and 1.</h5>

In [2]:
array_2 = np.random.rand(3)
print(array_2)

[0.64143457 0.67056754 0.89669968]


<h5>3. Create a 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations:</h5>

    - Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [3]:
array_3 = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])
first_two_rows = array_3[:2, :]
last_two_rows = array_3[1:, :]
print("First two rows:\n", first_two_rows)
print("Last two rows:\n", last_two_rows)

First two rows:
 [[10 20 45]
 [30 12 16]]
Last two rows:
 [[30 12 16]
 [42 17 56]]


<h5>4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.</h5>

In [4]:
array_4 = np.array([[1, 2], [3, 4]])
array_5 = np.array([[5, 6], [7, 8]])

# Vertical stacking
vertical_stack = np.vstack((array_4, array_5))
print("Vertically Stacked:\n", vertical_stack)

# Horizontal stacking
horizontal_stack = np.hstack((array_4, array_5))
print("Horizontally Stacked:\n", horizontal_stack)

# Here we split the array into 2 parts
split_1 = np.array_split(vertical_stack, 2)
split_2 = np.array_split(horizontal_stack, 2)

# Output the results
print("Split of Vertically Stacked:")
for i, arr in enumerate(split_1):
    print(f"Array {i+1}:\n{arr}")

print("Split of Horizontally Stacked:")
for i, arr in enumerate(split_2):
    print(f"Array {i+1}:\n{arr}")

Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally Stacked:
 [[1 2 5 6]
 [3 4 7 8]]
Split of Vertically Stacked:
Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]
Split of Horizontally Stacked:
Array 1:
[[1 2 5 6]]
Array 2:
[[3 4 7 8]]


<h5>5. Create two matrices 𝑋= ([[5,7,2],[4,5,6],[7,4 ,2]]), 𝑌= ([[4,2],[6,2],[4,2]])</h5>

    - Is it possible to multiply these matrices?
    - Demonstrate the case when it is not possible to.

In [5]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Check if multiplication is possible (X columns must match Y rows)
if X.shape[1] == Y.shape[0]:
    # Matrix multiplication is possible
    product = np.dot(X, Y)
    print("Matrix Multiplication Result:\n", product)
else:
    print("Matrix multiplication is not possible due to incompatible dimensions.")

# Demonstrating a case where multiplication is not possible
# Let's create another matrix Z with incompatible dimensions
Z = np.array([[1, 2], [3, 4]])  # 2x2 matrix

# Attempting multiplication with X (which is 3x3)
if X.shape[1] == Z.shape[0]:
    # Matrix multiplication would be possible
    product_incompatible = np.dot(X, Z)
    print("Matrix Multiplication with Z Result:\n", product_incompatible)
else:
    # Multiplication is not possible due to dimension mismatch
    print("Matrix multiplication with Z is not possible due to incompatible dimensions.")


Matrix Multiplication Result:
 [[70 28]
 [70 30]
 [60 26]]
Matrix multiplication with Z is not possible due to incompatible dimensions.


<h5>6. Create two arrays, 𝑥 = ([2,−1,−8]) 𝑦 = ([3,1,−2]),</h5>

    - Find the Shape, Number of dimensions of vector x.
    - Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [6]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Shape and number of dimensions of x
print("Shape of x:", x.shape)
print("Number of dimensions of x:", x.ndim)

# Reshape x and y
x_reshaped = x.reshape(3, 1)
y_reshaped = y.reshape(3, 1)
print("Reshaped x:\n", x_reshaped)
print("Reshaped y dimensions:", y_reshaped.ndim)


Shape of x: (3,)
Number of dimensions of x: 1
Reshaped x:
 [[ 2]
 [-1]
 [-8]]
Reshaped y dimensions: 2


<h5>7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.</h5>

Broadcasting is a powerful feature in NumPy that allows operations between arrays of different shapes by automatically expanding one of the arrays to match the shape of the other. This can simplify code and improve performance when working with arrays.

How Broadcasting Works:

Broadcasting Rules:
- If the two arrays differ in their number of dimensions, the smaller array is “padded” with ones on its left side until the shapes are compatible.
- Starting from the trailing (rightmost) dimension, NumPy compares the size of each dimension. Two dimensions are considered compatible if:
    - They are equal, or
    - One of them is 1.
- If the arrays are compatible, NumPy virtually stretches the smaller array across the larger one without actually copying the data, allowing element-wise operations to be performed.

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scalar = 2

# Subtraction and multiplication
subtracted = matrix - scalar
# The scalar 2 is treated as if it were a 3x3 matrix where every element is 2. This is because NumPy "stretches" the scalar across the matrix. Subtraction happens element-wise:
multiplied = matrix * scalar
# Similar to subtraction, the scalar 2 is broadcast across the matrix, and element-wise multiplication occurs:
print("Broadcasted subtraction:\n", subtracted)
print("Broadcasted multiplication:\n", multiplied)

Broadcasted subtraction:
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
Broadcasted multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


<h1>Part B- Linear Equations</h1>

<h5>Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using NumPy functions.</h5>

<h5>Part B.1</h5>

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

To solve this system, we can express it in matrix form 𝐴 ⋅ 𝑋 = 𝐵

A is the coefficient matrix,
X is the vector of variables [x,y,z],
B is the result vector.

Singularity check: If the determinant of the matrix 𝐴
A is zero, the system is singular, meaning there is no unique solution. Otherwise, we can solve it using np.linalg.solve().

In [8]:
import numpy as np

# Coefficient matrix A
A1 = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]])

# Result vector B
B1 = np.array([10, -4, 6])

# Check if the system is singular by calculating the determinant of A
det_A1 = np.linalg.det(A1)
print("Determinant of A1:", det_A1)

# Solve the system if it is non-singular
if det_A1 != 0:
    solution_1 = np.linalg.solve(A1, B1)
    print("Solution to the system:\n", solution_1)
else:
    print("The system is singular and cannot be solved.")

Determinant of A1: -70.00000000000003
Solution to the system:
 [ 1.8  2.4 -0.2]


<h5>Part B.2</h5>

1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

In [9]:
# Coefficient matrix A
A2 = np.array([[2, -1, 3, 4],
               [4, -2, 6, 8],
               [3, 1, -2, 2],
               [1, 3, -4, 1]])

# Result vector B
B2 = np.array([10, 20, 3, -1])

# Check the singularity of the matrix A
det_A2 = np.linalg.det(A2)
print("Determinant of A2:", det_A2)

# Solve the system if non-singular
if det_A2 != 0:
    solution_2 = np.linalg.solve(A2, B2)
    print("Solution to the system:\n", solution_2)
else:
    print("The system is singular and cannot be solved.")

Determinant of A2: 0.0
The system is singular and cannot be solved.


 In this case two of the equations are multiples of each other (equations 1 and 2), which could make the system singular (determinant = 0), resulting in no unique solution.